//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSV42_FullMapReplacement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSV42_FullMapReplacement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PATHS]
        ///MAPS=.\Maps
        ///MAPD=
        ///DATA=.\Data
        ///ROUTE=.\GDT
        ///GPS=.\CURGPS.INI
        ///USER=.\User
        ///CONTROL=.\
        ///LOGFILE=.\Logs
        ///JOBS=
        ///CUST=
        ///HTMLHELP=
        ///HELP=
        ///VVT=.\VVT
        ///ACROBAT=
        ///ACRODOCS=
        ///NOTES=.\Notes\Personal
        ///#NOTESUPLOAD=
        ///#NOTESDOWNLOAD=
        ///METAPATH=.\ExtDocs
        ///MFUPDATE=.\MFUpdates
        ///MFLASTUPDATEINI=.\MFUpdates\LastUpdate.INI
        ///UPDATEINFO=000001
        ///REDLINES=.\Personal
        ///AltSketchPaths=Redline\Individual|Redline\Shared\Working|Sketch\MapBased\Working|Redline\Shared\Incoming
        ///AUDIT_FILE=.\FSAudit*.xml
        ///ExtractPathCount=1        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DV32KY {
            get {
                return ResourceManager.GetString("DV32KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PATHS]
        ///MAPS=.\Maps
        ///MAPD=
        ///DATA=.\Data
        ///ROUTE=.\GDT
        ///GPS=.\CURGPS.INI
        ///USER=.\User
        ///CONTROL=.\
        ///LOGFILE=.\Logs
        ///JOBS=
        ///CUST=
        ///HTMLHELP=
        ///HELP=
        ///VVT=.\VVT
        ///ACROBAT=
        ///ACRODOCS=
        ///NOTES=.\Notes\Personal
        ///#NOTESUPLOAD=
        ///#NOTESDOWNLOAD=
        ///METAPATH=.\ExtDocs
        ///MFUPDATE=.\MFUpdates
        ///MFLASTUPDATEINI=.\MFUpdates\LastUpdate.INI
        ///UPDATEINFO=000001
        ///REDLINES=.\Personal
        ///AltSketchPaths=Redline\Individual|Redline\Shared\Working|Sketch\MapBased\Working|Redline\Shared\Incoming
        ///AUDIT_FILE=.\FSAudit*.xml
        ///ExtractPathCount=1        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DV32MS {
            get {
                return ResourceManager.GetString("DV32MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PATHS]
        ///MAPS=.\Maps
        ///MAPD=
        ///DATA=.\Data
        ///ROUTE=.\GDT
        ///GPS=.\CURGPS.INI
        ///USER=.\User
        ///CONTROL=.\
        ///LOGFILE=.\Logs
        ///JOBS=
        ///CUST=
        ///HTMLHELP=
        ///HELP=
        ///VVT=.\VVT
        ///ACROBAT=
        ///ACRODOCS=
        ///NOTES=.\Notes\Personal
        ///#NOTESUPLOAD=
        ///#NOTESDOWNLOAD=
        ///METAPATH=.\ExtDocs
        ///MFUPDATE=.\MFUpdates
        ///MFLASTUPDATEINI=.\MFUpdates\LastUpdate.INI
        ///UPDATEINFO=000001
        ///REDLINES=.\Personal
        ///AltSketchPaths=Redline\Individual|Redline\Shared\Working|Sketch\MapBased\Working|Redline\Shared\Incoming
        ///AUDIT_FILE=.\FSAudit*.xml
        ///ExtractPathCount=1        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DV32TX {
            get {
                return ResourceManager.GetString("DV32TX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PATHS]
        ///MAPS=.\Maps
        ///MAPD=
        ///DATA=.\Data
        ///ROUTE=.\GDT
        ///GPS=.\CURGPS.INI
        ///USER=.\User
        ///CONTROL=.\
        ///LOGFILE=.\Logs
        ///JOBS=
        ///CUST=
        ///HTMLHELP=
        ///HELP=
        ///VVT=.\VVT
        ///ACROBAT=
        ///ACRODOCS=
        ///NOTES=.\Notes\Personal
        ///#NOTESUPLOAD=
        ///#NOTESDOWNLOAD=
        ///METAPATH=.\ExtDocs
        ///MFUPDATE=.\MFUpdates
        ///MFLASTUPDATEINI=.\MFUpdates\LastUpdate.INI
        ///UPDATEINFO=000001
        ///REDLINES=.\Personal
        ///AltSketchPaths=Redline\Individual|Redline\Shared\Working|Sketch\MapBased\Working|Redline\Shared\Incoming
        ///AUDIT_FILE=.\FSAudit*.xml
        ///ExtractPathCount=1        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DV64BITKY {
            get {
                return ResourceManager.GetString("DV64BITKY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PATHS]
        ///MAPS=.\Maps
        ///MAPD=
        ///DATA=.\Data
        ///ROUTE=.\GDT
        ///GPS=.\CURGPS.INI
        ///USER=.\User
        ///CONTROL=.\
        ///LOGFILE=.\Logs
        ///JOBS=
        ///CUST=
        ///HTMLHELP=
        ///HELP=
        ///VVT=.\VVT
        ///ACROBAT=
        ///ACRODOCS=
        ///NOTES=.\Notes\Personal
        ///#NOTESUPLOAD=
        ///#NOTESDOWNLOAD=
        ///METAPATH=.\ExtDocs
        ///MFUPDATE=.\MFUpdates
        ///MFLASTUPDATEINI=.\MFUpdates\LastUpdate.INI
        ///UPDATEINFO=000001
        ///REDLINES=.\Personal
        ///AltSketchPaths=Redline\Individual|Redline\Shared\Working|Sketch\MapBased\Working|Redline\Shared\Incoming
        ///AUDIT_FILE=.\FSAudit*.xml
        ///ExtractPathCount=1        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DV64BITMS {
            get {
                return ResourceManager.GetString("DV64BITMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PATHS]
        ///MAPS=.\Maps
        ///MAPD=
        ///DATA=.\Data
        ///ROUTE=.\GDT
        ///GPS=.\CURGPS.INI
        ///USER=.\User
        ///CONTROL=.\
        ///LOGFILE=.\Logs
        ///JOBS=
        ///CUST=
        ///HTMLHELP=
        ///HELP=
        ///VVT=.\VVT
        ///ACROBAT=
        ///ACRODOCS=
        ///NOTES=.\Notes\Personal
        ///#NOTESUPLOAD=
        ///#NOTESDOWNLOAD=
        ///METAPATH=.\ExtDocs
        ///MFUPDATE=.\MFUpdates
        ///MFLASTUPDATEINI=.\MFUpdates\LastUpdate.INI
        ///UPDATEINFO=000001
        ///REDLINES=.\Personal
        ///AltSketchPaths=Redline\Individual|Redline\Shared\Working|Sketch\MapBased\Working|Redline\Shared\Incoming
        ///AUDIT_FILE=.\FSAudit*.xml
        ///ExtractPathCount=1        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DV64BITTX {
            get {
                return ResourceManager.GetString("DV64BITTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [General]
        ///Enable On Startup=0
        ///Baud Rate=4800
        ///COM Port=99
        ///Parity=0
        ///Update Interval=1
        ///Log Interval=2
        ///GPS_FORMAT=2
        ///INTERVAL_FORMAT=0
        ///LENGTH_INTERVAL=3
        ///DISTANCE_INTERVAL=5
        ///Log File=****
        ///HIST_FILE_MAX_DAYS=1
        ///ENABLE_EDIT_SETTINGS=0
        ///
        ///#TIME_OUT should be in seconds
        ///TIME_OUT=60
        ///Enable Auto Scan=0
        ///
        ///[APP]
        ///Name=FieldSmart View
        ///.
        /// </summary>
        internal static string gps {
            get {
                return ResourceManager.GetString("gps", resourceCulture);
            }
        }
    }
}
